movieapp/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
app_name='movieapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movieapp/models.py
from django.db import models

class Movie(models.Model):
    name=models.CharField(max_length=50)
    description=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieapp/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','description','year','img']

movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import MovieForm
from .models import Movie

def index(request):
    movie=Movie.objects.all()
    content={
        'movie_info':movie
    }
    return render(request,'index.html',content)
def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"detial.html",{'movie':movie})
def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name')
        description = request.POST.get('description')
        year = request.POST.get('year')
        img = request.FILES['img']
        movie=Movie(name=name,description=description,year=year,img=img)
        movie.save()

    return render(request,'add.html')
def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})


def delete(request, id):
    if request.method =='POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="enter your movie name"><br>
  <input type="text" name="description" placeholder="enter your description"><br>
  <input type="text" name="year" placeholder="enter your movie year"><br>
  <input type="file" name="img" ><br>
  <input type="submit">


</form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">ONLINE MOVIE STORE</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav" >
    <ul class="navbar-nav" style="text-align:right;">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>

    </ul>
  </div>
</nav>
{% block body %}
{% endblock %}

</body>
</html>

templates/delete.html
<form method="POST">
    {% csrf_token %}
    Are you want to delete this movie?<br>
    <input type="submit">
</form>

templates/detial.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="300" height="300"}>
        </div>
<div class="col-md-6 text-white">
    <p>MOVIE NAME :{{movie.name}}</p><br>
    <p>DESCRIPTION :{{movie.description}}</p><br>
    <p>YEAR :{{movie.year}}</p><br>
    <a class="btn btn-warning " href="{% url 'movieapp:update' movie.id %}">UPDATE</a>
    <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">DELETE</a>
</div>


    </div>
</div>
{% endblock %}

templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}<br>
    <input type="submit">
</form>

templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in movie_info %}
           <div class="card bg-dark" style="width: 18rem;margin:10px;">
               <img class="card-img-top" src="{{i.img.url}}"  alt="Card image cap" width="100" height="200">
               <div class="card-body bg-dark text-white ">
                 <h5 class="card-title">{{i.name}}</h5>
                 <p class="card-text">{{i.description}}</p>
                 <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
        {% endfor %}
    </div>
</div>


{% endblock %}